### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by muhammadkhan** [muhammadkhan/Curriculum-ViTeX#3]
Write up:
- an instruction manual for Curriculum ViTeX, which provides an RML tutorial and a structure.xml tutorial, among other things
- document the code

**Comment by aabiddanda** [comment]
Would it be possible to provide a quick example at the very end of the documentation for an entire run through of the entire procedure? I am currently running:

`./cvitex.sh doc/samples/rml_sample.rml tccv`

In order to generate a .tex file. Putting this explicit command in the documentation would help a lot I think.

**Comment by aabiddanda** [comment]
Also as a side-comment, in the sample .rml file provided the inclusion of "infinity^2" as a float value throws a python ValueError for me. I changed it to a regular "infinity" and it worked just fine. 

![screen shot 2015-08-06 at 10 49 34 am](https://cloud.githubusercontent.com/assets/2427335/9114637/e20d8a3a-3c28-11e5-8a2a-7806bbb9d18d.png)

**Comment by muhammadkhan** [comment]
Thanks - I took care of these

**Comment by muhammadkhan** [comment]
Wrote sufficient docs finally -_-
